name: 'Manual e2e execution'

on:
  workflow_dispatch:
    inputs:
      motivation:
        required: true
        description: 'Motivo da execução?'

jobs:
  test:
    name: E2E test execution
    runs-on: ubuntu-20.04
    steps:
      - name: Test running motivation
        run: |
          echo "Name: ${{ github.event.inputs.motivation }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Setup Playwright
        run: yarn setup

      - name: Run tests
        run: yarn test --project chromium

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure History
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 100

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true